main/urls.py
from django.urls import path
from . import views


app_name = 'main'
urlpatterns = [
    path('about/', views.About.as_view(), name='about'),
]

symposium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import main.views

handler404 = main.views.handler404
handler500 = main.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('uni.urls')),

]

if settings.DEBUG:
    mediaurl = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += mediaurl

uni/urls.py
from django.urls import path
from . import views

app_name = "uni"

urlpatterns = [
    path('template/', views.GTemplate.as_view(),),
    path('', views.Login.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.Register.as_view(), name='register'),
    path('activate/<slug:link>/', views.Activate.as_view(), name='activate'),
    path('send-reset-link/', views.SendPasswordReset.as_view(),
         name='reset-link'),
    path('reset/<slug:link>/', views.PasswordReset.as_view(), name='reset'),
    path('class-heads/authorize/',
         views.LeaderAuthorization.as_view(), name='leader-authorize'),
    path('class/<slug:name>/', views.ClassPage.as_view(),
         name='class-index'),
    path('class/create/', views.CreateSymposium.as_view(),
         name='create-class'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('profile/', views.Profile.as_view(), name='profile'),
    path('profile/update-user-info/', views.updated_user_info,
         name='update-user-info'),
    path('profile/add-number/', views.add_phone_number,
         name='add-number'),
    path('profile/remove-number/<str:id>/', views.remove_phone_number,
         name='remove-number'),
    path('class-groups/expore/', views.ExploreSymposium.as_view(),
         name='explore-classes'),
    path('class-groups/join/<str:pk>/', views.join_symposium,
         name='join-class'),
    path('FAQs/', views.FAQView.as_view(), name='faqs'),
    path('assignments/<str:pk>', views.AssignmentView.as_view(),
         name='assignment'),
    path('timetable/add/', views.add_timetable,
         name='add-timetable'),
    path('timetable/remove/<str:pk>', views.delete_timetable,
         name='delete-timetable'),
    path('assignment/add/', views.add_assignment,
         name='add-assignment'),
    path('assignment/remove/<str:pk>', views.remove_assignment,
         name='remove-assignment'),
]

main/models.py
from django.db import models

# Create your models here.


class SiteInfo(models.Model):
    """
    Model holds all the information about
    The symposium website

    Note: This models should only have one instance.
    a `SiteInfo.objects.get` method is used in the
    view.py which breaks if multiple instance is
    returned.
    """
    name = models.CharField(max_length=100,
                            help_text="Name of the website")
    favicon = models.FileField()
    apple_icon = models.ImageField(blank=True)
    logo = models.ImageField()
    source_code_link = models.URLField(blank=True)
    about = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        if SiteInfo.objects.count() > 1:
            return
        super(SiteInfo, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class SocialAccount(models.Model):
    """
    This model holds all the
    social accout info for the
    site.
    """
    SOCIAL_MEDIA_OPTIONS = (
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
        ('twitter', 'Twitter'),
        ('whatsapp', 'Whatsapp'),
        ('telegram', 'Telegram'),
        ('tik_tok', 'Tik Tok'),
    )
    site = models.ForeignKey(SiteInfo,
                             on_delete=models.CASCADE,
                             related_name='social_accounts')
    account = models.CharField(max_length=100, choices=SOCIAL_MEDIA_OPTIONS)
    link = models.URLField()

    def __str__(self):
        return self.account

uni/models.py
from django.db import models
from django.contrib.auth import get_user_model
import secrets
import datetime as dt
from django.utils.timezone import make_aware
import logging
from io import BytesIO
from PIL import Image
from django.core.files.base import ContentFile
from django.utils.text import slugify

# default user model.
USER = get_user_model()

logger = logging.getLogger(__name__)


class ImageCompressMixin:
    """
    Mixin to compress models
    `ImageField`
    """

    def _compress_img(self, img, quality=20, format='JPEG'):
        """
        Function helps in the reduction of image
        quality
        """
        logger.info("Compressing image")
        img = Image.open(img)
        compressed_img = BytesIO()
        img.save(compressed_img, quality=quality, format=format)
        compressed_img.seek(0)
        return compressed_img

    def compress_img(self, field):
        """
        Compresses the image of the
        field specified
        """
        if bool(field):  # Used bool to test if the field is None,
            # field is None doesn't yield expected result.
            compressed = self._compress_img(img=field)
            field.save(
                field.name,
                ContentFile(compressed.read()),
                save=False,
            )
            compressed.close()


class Faculty(models.Model):
    """
    Holds Informations about
    facluties present in the
    university.
    """
    name = models.CharField(max_length=50,)
    about = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Faculties"


class Lecturer(models.Model):
    """
    `Lecturer` models represents a
    university's Lecturer.
    """
    basic_data = models.ForeignKey(USER, on_delete=models.CASCADE, blank=True)

    def __str__(self):
        return self.basic_data.first_name or "Unidentified Lecturer"


class Department(models.Model):
    """
    Model for all the Departments
    the university has.
    """
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE,
                                related_name='departments')
    name = models.CharField(max_length=100)
    about = models.TextField(blank=True)
    HOD = models.ForeignKey(Lecturer, on_delete=models.SET_NULL, null=True,
                            blank=True)

    def __str__(self):
        return self.name


class Course(ImageCompressMixin, models.Model):
    faculty = models.ForeignKey(Faculty, null=True, on_delete=models.SET_NULL,
                                related_name='courses', blank=True)
    department = models.ForeignKey(Department, null=True,
                                   on_delete=models.SET_NULL,
                                   related_name='courses', blank=True)
    code = models.CharField(max_length=10, help_text="e.g MAT-101 \
    (all capital letters)")
    name = models.CharField(max_length=100, blank=True)
    about = models.TextField(blank=True)
    poster_image = models.ImageField(blank=True)

    def __str__(self):
        return self.code

    def save(self, *args, **kwargs):
        self.compress_img(self.poster_image)
        super().save()


class Symposium(ImageCompressMixin, models.Model):
    """
    Ignore it's unusual name. This
    models is models the Class in which
    all students belong to.

    Notice: The class name `Symposium`
    might be deprecated when a better name
    comes along.
    """
    LEVEL_OPTIONS = (
        ('100', '100 Level'),
        ('200', '200 Level'),
        ('300', '300 Level'),
        ('400', '400 Level'),
        ('500', '500 Level'),
    )
    department = models.ForeignKey(Department, on_delete=models.CASCADE,
                                   related_name='classes')
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(blank=True)
    level = models.CharField(max_length=3, choices=LEVEL_OPTIONS)
    about = models.TextField(blank=True)
    poster_image = models.ImageField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.compress_img(self.poster_image)
        self.slug = slugify(self.name)
        super().save()

    class Meta:
        ordering = ['-created_on']


class SymposiumBroadcast(models.Model):
    """
    Model is used by Class Governors and
    Deputy to send broadcast message
    that propagates to all members of a `Symposium`
    i.e students. it expires after 24hrs
    """

    FROM_OPTIONS = (
        ('G', 'Governor'),
        ('D', 'Deputy Governor'),
    )
    symposium = models.OneToOneField(Symposium, on_delete=models.CASCADE,
                                     related_name='broadcast')
    message = models.CharField(max_length=220)
    message_from = models.CharField(max_length=1, choices=FROM_OPTIONS,
                                    default='G')
    created_on = models.DateTimeField(auto_now_add=True)
    expire_by = models.DateTimeField(blank=True)

    def remove_expired(self):
        if(self.expire_by <= make_aware(dt.datetime.now())):
            self.delete()
        return True

    def __str__(self):
        return str(self.symposium)


class OfferedCourse(models.Model):
    symposium = models.ForeignKey(Symposium, on_delete=models.CASCADE,
                                  related_name='courses')
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    unit = models.IntegerField(blank=True)

    def __str__(self):
        return f"{self.symposium} => {self.course}"


class AssignmentManager(models.Manager):
    def now_and_future(self):
        """
        Archives `Assignment` with
        `submission_date` older than current date and
        filters `Assignment` to return
        those with dates matching the current
        date and future dates.
        """
        old_assigments = self.filter(submission_date__lt=make_aware(
            dt.datetime.now()))
        for assignment in old_assigments:
            assignment.archive = True
            assignment.save()
        nf = make_aware(dt.datetime.now())
        return self.filter(submission_date__gte=nf)


class Assignment(models.Model):
    objects = AssignmentManager()

    symposium = models.ForeignKey(Symposium, on_delete=models.CASCADE,
                                  related_name='assignments', blank=True, null=True)
    course = models.ForeignKey(OfferedCourse, on_delete=models.CASCADE,
                               related_name='assignments')
    questions = models.TextField()
    submission_date = models.DateTimeField()
    archive = models.BooleanField(default=False)

    def __str__(self):
        return str(self.course)


class Timetable(models.Model):
    symposium = models.OneToOneField(Symposium, on_delete=models.CASCADE,
                                     related_name='timetable')

    def __str__(self):
        return str(self.symposium)


class TimetableUnitManager(models.Manager):
    def now_and_future(self):
        """
        Archives `TimetableUnit` with
        date older than current date and
        filters `TimetableUnit` to return
        those with dates matching the current
        date and future dates.
        """
        old_timetable_unit = self.filter(date_time__lt=make_aware(
            dt.datetime.now()))
        for unit in old_timetable_unit:
            unit.archive = True
            unit.save()
        nf = make_aware(dt.datetime.now())
        return self.filter(date_time__gte=nf)


class TimetableUnit(models.Model):
    objects = TimetableUnitManager()
    TYPE_OPTIONS = (
        ('L', 'Lecture'),
        ('T', 'Tutorial'),
        ('E', 'Exam'),
        ('P', 'Practical'),
    )
    timetable = models.ForeignKey(Timetable, on_delete=models.CASCADE,
                                  related_name='units', blank=True, null=True)
    course = models.ForeignKey(OfferedCourse, on_delete=models.CASCADE,
                               related_name='timetable', blank=True)
    unit_type = models.CharField(max_length=1, choices=TYPE_OPTIONS)
    date_time = models.DateTimeField()
    duration = models.DurationField(blank=True)
    archive = models.BooleanField(default=False)

    def __str__(self):
        return str(self.timetable)


class FAQ(models.Model):
    symposium = models.ForeignKey(Symposium, on_delete=models.CASCADE,
                                  related_name='faqs')
    question = models.CharField(max_length=100)
    answer = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

    class Meta:
        ordering = ['-created_on']


class Student(ImageCompressMixin, models.Model):
    """
    `Student` model represents each university student member
    and holds their data.
    """
    GENDER_OPTIONS = (
        ('m', 'Male'),
        ('f', 'Female'),
        ('r', 'Rather not say'),
    )

    RELIGION_OPTIONS = (
        ('c', 'Christianity'),
        ('i', 'Islam'),
        ('r', 'Rather not say')
    )

    STATE_OPTIONS = (
        ('abia', 'Abia'),
        ('adamawa', 'Adamawa'),
        ('akwa ibom', 'Akwa Ibom'),
        ('anambra', 'Anambra'),
        ('bauchi', 'Bauchi'),
        ('bayelsa', 'Bayelsa'),
        ('benue', 'Benue'),
        ('borno', 'Borno'),
        ('cross river', 'Cross River'),
        ('delta', 'Delta'),
        ('ebonyi', 'Ebonyi'),
        ('edo', 'Edo'),
        ('ekiti', 'Ekiti'),
        ('enugu', 'Enugu'),
        ('gombe', 'Gombe'),
        ('imo', 'Imo'),
        ('jigawa', 'Jigawa'),
        ('kaduna', 'Kaduna'),
        ('kano', 'Kano'),
        ('katsina', 'Katsina'),
        ('kebbi', 'Kebbi'),
        ('kogi', 'Kogi'),
        ('kwara', 'Kwara'),
        ('lagos', 'Lagos'),
        ('nasarawa', 'Nasarawa'),

uni/templates/uni/class-factory.html
{% extends 'uni/form_base.html' %}
{% block title %}The Symposium Factory{% endblock title %}

{% block form_method %}POST{% endblock form_method %}
{% block form_action %}{% endblock form_action %}
{% block form_extras %}enctype="multipart/form-data"{% endblock form_extras %}
{% block form_fields %}
<div class="alert alert-info" role="alert">
  <div class="container">
    <div class="alert-icon">
      <i class="now-ui-icons travel_info"></i>
    </div>
    <strong>Notice!</strong> Class groups should only be created once by the
    class governor, all other class members including the class deputy are required to join this class group.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">
        <i class="now-ui-icons ui-1_simple-remove"></i>
      </span>
    </button>
  </div>
</div>
<h3>Create Class Group</h3>

<div class="form-group">
  <label for="rank">Department</label>
  <select class="form-control" id="rank" name="department">
    {% for x, y in form.fields.department.choices %}
    <option value="{{ x }}" {% if form.fields.department.value == x %} selected{% endif %}>{{ y }}</option>
    {% endfor %}
  </select>
</div>

<div class="input-group no-border input-lg">
  <div class="input-group-prepend">
    <span class="input-group-text">
      <i class="now-ui-icons travel_istanbul"></i>
    </span>
  </div>
  <input type="text" class="form-control" placeholder="Class name..." name="name" value="{% if form.name.value is not None %}{{ form.name.value }}{% endif %}">
</div>

<div class="form-group">
  <label for="rank">Level</label>
  <select class="form-control" id="rank" name="level">
    {% for x, y in form.fields.level.choices %}
    <option value="{{ x }}" {% if form.fields.level.value == x %} selected{% endif %}>{{ y }}</option>
    {% endfor %}
  </select>
</div>

<div class="form-group">
  <label for="about">About Class</label>
  <textarea class="form-control" id="id_about" rows="1" name="about"></textarea>
</div>

<div>
  <p><label for="id_poster_image">Poster image:</label> <input type="file" name="poster_image" accept="image/*" id="id_poster_image"></p>
</div>

{% endblock form_fields %}

{% block submit_button_text %}Create Class{% endblock submit_button_text %}

uni/templates/uni/dash_base.html
<!--

=========================================================
* Now UI Dashboard - v1.5.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-dashboard
* Copyright 2019 Creative Tim (http://www.creative-tim.com)

* Designed by www.invisionapp.com Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'uni/images/logo.svg' %}">
  <link rel="icon" href="{% static 'uni/images/favicon.svg' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    {% block title %}{{ request.user.first_name }}'s Dashboard{% endblock title %}
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <!-- CSS Files -->
  <link href="{% static 'uni/css/bootstrap.min.css' %}" rel="stylesheet" />
  <link href="{% static 'uni/css/now-ui-dashboard.css' %}?v=1.5.0" rel="stylesheet" />

  <!-- Katex CSS files -->
  <link rel="stylesheet" href="{% static 'uni/katex/katex.min.css' %}">
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="orange">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="blue | green | orange | red | yellow"
    -->
      <div class="logo">
        <a href="{% url 'main:about' %}" class="simple-text logo-mini" title="about {{ site_info.name }}">
          <i class="fa fa-school"></i>
        </a>
        <a href="{% if request.user.member_of is not None %}{% url 'uni:class-index' name=request.user.student_data.member_of.slug %}{% endif %}" class="simple-text logo-normal">
          Class Page
        </a>
      </div>
      <div class="sidebar-wrapper" id="sidebar-wrapper">
        <ul class="nav">
          <li class="{% if request.get_full_path == '/dashboard/' %}active{% endif %}">
            <a href="{% url 'uni:dashboard' %}">
              <i class="now-ui-icons design_app"></i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="{% if request.get_full_path == '/profile/' %}active{% endif %}">
            <a href="{% url 'uni:profile' %}">
              <i class="now-ui-icons users_single-02"></i>
              <p>User Profile</p>
            </a>
          </li>
          <li class="{% if request.get_full_path == '/class-groups/expore/' %}active{% endif %}">
            <a href="{% url 'uni:explore-classes' %}">
              <i class="now-ui-icons education_atom"></i>
              <p>Explore Class Groups</p>
            </a>
          </li>
          {% if request.user.student_data.member_of != '' or request.user.student_data.member_of is not None %}
          <li class="{% if request.get_full_path == '/FAQs/' %}active{% endif %}">
            <a href="{% url 'uni:faqs' %}">
              <i class="now-ui-icons location_map-big"></i>
              <p>FAQs</p>
            </a>
          </li>
          {% endif %}
          <li>
            <a href="">
              <i class="now-ui-icons ui-1_bell-53"></i>
              <p>Market place</p>
            </a>
          </li>
          <li>
            <a href="">
              <i class="now-ui-icons ui-1_bell-53"></i>
              <p>News Hub</p>
            </a>
          </li>
          <li>
            <a href="">
              <i class="now-ui-icons ui-1_bell-53"></i>
              <p>Forums</p>
            </a>
          </li>
          <li>
            <a href="">
              <i class="now-ui-icons ui-1_bell-53"></i>
              <p>Resourses & Archives</p>
            </a>
          </li>
          <li>
            <a href="">
              <i class="now-ui-icons ui-1_bell-53"></i>
              <p>Payments</p>
            </a>
          </li>
          <li class="active-pro">
            <a href="">
              <i class="now-ui-icons ui-1_settings-gear-63"></i>
              <p>Settings</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel" id="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent  bg-primary  navbar-absolute">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="#">{% if request.get_full_path == '/dashboard/' %}{{ request.user.first_name }}'s Dashboard{% endif %}</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end" id="navigation">
            <form>
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <div class="input-group-append">
                  <div class="input-group-text">
                    <i class="now-ui-icons ui-1_zoom-bold"></i>
                  </div>
                </div>
              </div>
            </form>
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#">
                  <i class="now-ui-icons business_bank"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Class Page</span>
                  </p>
                </a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="now-ui-icons design_bullet-list-67"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Menu</span>
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="{% url 'uni:logout' %}">Logout</a>
                </div>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="modal" data-target="#profileInfo">
                  <i class="now-ui-icons users_single-02"></i>
                  <p>
                    <span class="d-lg-none d-md-block">Profile Info</span>
                  </p>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <!-- Modal -->
      <div class="modal fade" id="profileInfo" tabindex="-1" role="dialog" aria-labelledby="porfileInfox" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="profileInfoLabel">Profile Info</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Matric No: </strong>{{ request.user.student_data.matric_no }}</li>
                <li class="list-group-item"><strong>Reg No: </strong>{{ request.user.student_data.reg_no }}</li>
                <li class="list-group-item"><strong>Class Group: </strong>{{ request.user.student_data.member_of.name }}</li>
              </ul>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>
      <div class="panel-header panel-header-sm mb-5">
        <div class="container">
          <div class="row">
          </div>
          <div class="row">
            {% if request.user.student_data.member_of.broadcast.remove_expired %}
            <div class="card">
              <div class="card-body">
                <blockquote class="blockquote blockquote-primary mb-0">
                  <p>{{ request.user.student_data.member_of.broadcast.message }}</p>
                  <footer class="blockquote-footer">Broadcast message from {{ request.user.student_data.member_of.broadcast.get_message_from_display }}</footer>
                </blockquote>
              </div>
            </div>
            {% endif %}

          </div>
        </div>
      </div>
      {% block content %}{% endblock content %}
      <footer class="footer">
        <div class=" container ">
          <nav>
            <ul>
              <li>
                <a href="{% url 'main:about' %}">
                  About
                </a>
              </li>
              <li>
                <a href="#">
                  Contributors
                </a>
              </li>
              <li>
                <a href="#">
                  Donate
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright" id="copyright">
            &copy;
            <script>
              document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))
            </script>, Designed by
            <a href="https://www.invisionapp.com" target="_blank">Invision</a>. Coded by
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a>.
          </div>
        </div>
      </footer>
    </div>
  </div>

  <!--   Core JS Files   -->
  <script src="{% static 'uni/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'uni/js/core/popper.min.js' %}"></script>
  <script src="{% static 'uni/js/core/bootstrap.min.js' %}"></script>
  <script src="{% static 'uni/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>

  <!-- Chart JS -->
  <script src="{% static 'uni/js/plugins/chartjs.min.js' %}"></script>

  <!--  Notifications Plugin    -->
  <script src="{% static 'uni/js/plugins/bootstrap-notify.js' %}"></script>

  <!-- Control Center for Now Ui Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'uni/js/now-ui-dashboard.min.js' %}?v=1.5.0" type="text/javascript"></script>
  <script src="{% static 'uni/katex/katex.min.js' %}" charset="utf-8"></script>
  <script src="{% static 'uni/katex/contrib/mhchem.min.js' %}" charset="utf-8"></script>
  <script src="{% static 'uni/katex/contrib/auto-render.min.js' %}" charset="utf-8"></script>
  <script src="{% static 'uni/js/auto-render-katex.js' %}" charset="utf-8"></script>
  <script type="text/javascript">
    $(document).ready(function() {
      {% for message in messages %}
      setTimeout(1000, nowuiDashboard.showNotification(
        'top',
        'right',
        "{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}",
        "now-ui-icons travel_info",
        '{{ message }}'));
        {% endfor %}
    });
  </script>
  {% block script %}{% endblock script %}
</body>

</html>

uni/templates/uni/login.html
{% extends 'uni/form_base.html' %}
{% block title %}Login to The Symposium{% endblock title %}

{% block form_method %}POST{% endblock form_method %}
{% block form_action %}{% url 'uni:login' %}{% endblock form_action %}
{% block form_fields %}

<span class="text-white">
  <marquee behavior="rtl">Please login with your email or username if you haven't updated your profile with a matric no or reg no.</marquee>
</span>
<div class="input-group no-border input-lg">
  <div class="input-group-prepend">
    <span class="input-group-text">
      <i class="now-ui-icons users_circle-08"></i>
    </span>
  </div>
  <input type="text" class="form-control" placeholder="Email/Username/Matric No/Reg No..." name="multi_field" value="{% if form.multi_field.value is not None %}{{ form.multi_field.value }}{% endif %}">
</div>


<div class="input-group no-border input-lg">
  <div class="input-group-prepend">
    <span class="input-group-text">
      <i class="now-ui-icons users_circle-08"></i>
    </span>
  </div>
  <input type="password" class="form-control" placeholder="Password..." name="password">
</div>

{% endblock form_fields %}

{% block submit_button_text %}Login{% endblock submit_button_text %}